require("@rails/ujs").start()
require("turbolinks").start()
require("@rails/activestorage").start()
require("channels")
require("bootstrap/dist/js/bootstrap")

require("packs/maps/onClick.js")
require("packs/maps/setId.js")
require("packs/maps/initMap.js")
require("packs/maps/button.js")