require("@rails/ujs").start()
require("turbolinks").start()
require("@rails/activestorage").start()
require("channels")
require("jquery")
require("bootstrap/dist/js/bootstrap")

require("./maps/onClick.js")
require("./maps/button.js")
require("./maps/makePin.js")